### ISSUE TITLE
Meteor issue

### ISSUE THREAD

**Issue by marcianosr** [danialfarid/ng-file-upload#880] opened 2015-07-17 15:09 UTC
Hi, 

I'm currently building an app with Meteor-Angular. I'm trying to implement the file upload but I keep getting the following error when I try to upload an image file: 

<pre>TypeError: undefined is not a function
    at ng-file-upload-all.js:579
    at angular.js:9341
    at forEach (angular.js:336)
    at transformData (angular.js:9340)
    at $get.serverRequest (angular.js:10031)
    at processQueue (angular.js:14569)
    at angular.js:14585
    at Scope.$get.Scope.$eval (angular.js:15848)
    at Scope.$get.Scope.$digest (angular.js:15659)
    at Scope.$get.Scope.$apply (angular.js:15953)</pre>

Here is my code: 

html:
```<div class="btn btn-primary" ngf-select ngf-change="upload($files)">Select File</div>```

javascript: 
```
		$scope.upload = function(files) { 

			if (files && files.length) {
	            for (var i = 0; i < files.length; i++) {
	                var file = files[i];
	                console.log(file)
	                Upload.upload({
	                    url: '/uploads',
	                    file: files
	                }).progress(function (evt) {
	                    var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
	                    $scope.log = 'progress: ' + progressPercentage + '% ' +
	                                evt.config.file.name + '\n' + $scope.log;
	                }).success(function (data, status, headers, config) {
	                    $timeout(function() {
	                        $scope.log = 'file: ' + config.file.name + ', Response: ' + JSON.stringify(data) + '\n' + $scope.log;
	                    });
	                });
	            }
	        }
		}
```

Any idea whats causing it? 

Thanks for reading,

**Comment by danialfarid** [comment] 2015-07-17 15:13
What browser?

**Comment by marcianosr** [comment] 2015-07-17 15:52
Chrome

**Comment by danialfarid** [comment] 2015-07-17 16:33
what version of the plugin

**Comment by danialfarid** [comment] 2015-07-17 16:34
Seems like for some reasons FormData is not defined in your browser.

**Comment by marcianosr** [comment] 2015-07-17 19:34
Yeah, I see now. But it also happens with IE. 

As for the version, it is 5.0.9

**Comment by danialfarid** [comment] 2015-08-03 20:29
Can you create a jsfiddle? It might be specific to your browser some plugins or something. Otherwise you should be able to create a jsfiddle and I would work on fixing it.

**Comment by danialfarid** [comment] 2015-09-26 19:09
I believe the problem is that you are not loading the shim file. Make sure the shim file is loaded before ng-file-upload.js.

**Comment by sean-stanley** [comment] 2015-11-16 01:05
Just having this issue as well.
this may be a meteor.js specific issue as FormData is definately defined in the latest versions of Chrome. When I have the error I can still type `var f = new FormData()` and I get a formData object.

Also, to make sure the shim gets loaded @danialfarid should modify the package.js file served on atmosphere to load and compile the shim at run-time. Also, the loaded files should be non-minified versions as meteor handles resource aggregation and minification for us.

 I am happy to help with meteor configuration. And it could be a meteor issue instead.

**Comment by danialfarid** [comment] 2015-11-16 17:29
Shim file is an optional include. If you are not supporting IE8-9 then you won't need that file.

**Comment by sean-stanley** [comment] 2015-11-16 19:12
You're right. Adding the shim file to my project didn't work. I even tried a different package that included the ng-upload-all.js and that didn't work. I actually got a totally different error there. Anyway, I am trying to create a meteor pad test for you to recreate the problem. I'll post it here when it's done or would you prefer a new issue for this?

**Comment by danialfarid** [comment] 2015-11-16 19:36
Here should be fine if it is related to this issue.

**Comment by danialfarid** [comment] 2015-11-16 21:05
https://github.com/percolatestudio/atmosphere/issues/415

**Comment by danialfarid** [comment] 2015-12-02 20:30
@marcianosr @sean-stanley Could you guys try out this package https://atmospherejs.com/danialf/ng-file-upload and see if it works? Wanna make sure I have set it up properly.

**Comment by sean-stanley** [comment] 2015-12-02 20:48
Hi just tried it out in a meteor-based reproduction of one of the plunkr examples and unfortunately I got this error:

**Comment by sean-stanley** [comment] 2015-12-02 20:48
```
/Users/seanstanley/.meteor/packages/meteor-tool/.1.1.10.1miu1ox++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151203-09:44:51.687(13)? (STDERR) 						throw(ex);
W20151203-09:44:51.687(13)? (STDERR) 						      ^
W20151203-09:44:51.743(13)? (STDERR) ReferenceError: window is not defined
W20151203-09:44:51.743(13)? (STDERR)     at packages/danialf_ng-file-upload/ng-file-upload-all.js:23:1
W20151203-09:44:51.743(13)? (STDERR)     at Package (packages/danialf_ng-file-upload/ng-file-upload-all.js:230:1)
W20151203-09:44:51.743(13)? (STDERR)     at /Users/seanstanley/sites/ng-upload demo/.meteor/local/build/programs/server/packages/danialf_ng-file-upload.js:2486:4
W20151203-09:44:51.743(13)? (STDERR)     at /Users/seanstanley/sites/ng-upload demo/.meteor/local/build/programs/server/packages/danialf_ng-file-upload.js:2493:3
W20151203-09:44:51.743(13)? (STDERR)     at /Users/seanstanley/sites/ng-upload demo/.meteor/local/build/programs/server/boot.js:242:10
W20151203-09:44:51.743(13)? (STDERR)     at Array.forEach (native)
W20151203-09:44:51.743(13)? (STDERR)     at Function._.each._.forEach (/Users/seanstanley/.meteor/packages/meteor-tool/.1.1.10.1miu1ox++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151203-09:44:51.743(13)? (STDERR)     at /Users/seanstanley/sites/ng-upload demo/.meteor/local/build/programs/server/boot.js:137:5
```

**Comment by danialfarid** [comment] 2015-12-02 20:56
Could you help me out setting up package.js properly?
https://github.com/danialfarid/ng-file-upload-bower/blob/master/package.js
I think the problem is there.

**Comment by danialfarid** [comment] 2015-12-02 20:56
You can submit a pull request for that file

**Comment by danialfarid** [comment] 2015-12-03 15:35
Can you post the plunkr url here @sean-stanley

**Comment by danialfarid** [comment] 2015-12-03 16:33
Ok it should be fixed now. Try version 10.1.7

**Closed by danialfarid** 2015-12-03 16:33 UTC
