### ISSUE TITLE
why width > 1000 doing auto resiz?

### ISSUE THREAD

**Issue by armangevorgyan** [danialfarid/ng-file-upload#1172] opened 2015-12-01 06:38 UTC
why height=1000px width=8000px => console show ngfWidth = 1351, ngfHeight = 169

**Comment by danialfarid** [comment] 2015-12-01 06:46
post your code

**Comment by armangevorgyan** [comment] 2015-12-01 09:55
<button class="button" accept="image/*"
      ngf-select="main.uploadImages($files)"
                           name="browse"
                           ngf-pattern="'.jpg,.png,.jpeg'"
                           ngf-max-size="50MB"
                           ngf-max-height="10000"
                           ngf-min-height="1000"
                           ngf-min-width="1000"
                           ngf-max-width="10000"
                           ng-model="files"
                           multiple="multiple"
                           ng-model-options="{allowInvalid: true}" >   Browse   </button>

/////////////////////////////////////////////////
 if (this.verifyImage(file)) {
                        images.push(file);
                        this.log.debug('Valid images', 'ratio', file.$ngfWidth / file.$ngfHeight, 'width', file.$ngfWidth, "height", file.$ngfHeight)
                        this.Upload.upload({
                            url: art7.API.artwork.getProjects.url,
                            data: {file: images}
                        })

**Comment by danialfarid** [comment] 2015-12-01 18:18
So what the problem is?

**Comment by armangevorgyan** [comment] 2015-12-02 06:54
Problem : when height >= 1000 width < = 1000 its okay, but when width > 1000 ,  when i take width and height there are resized . example width 8000 height 1000 => ngfWidth =   1351, ngfHeight = 169,
width 1000 height 8000 => ngfWidth =   1000, ngfHeight = 8000, why??

**Comment by danialfarid** [comment] 2015-12-02 07:31
Don't rely on `ngfWidth` for the actual width or height. Those are just for internal use and might be removed later on. 
If you use that image in any other places like `ngf-thumbnail` it could resize it again and those values would change.

**Comment by danialfarid** [comment] 2015-12-02 07:31
You can use `Upload.imageDimensions()` service to get the actual image dimensions of the file.

**Comment by armangevorgyan** [comment] 2015-12-02 08:38
no i didn't use ngf-thumbnail. i want check ngf-min-width="1000" , ngf-max-width="10000",ngf-max-height="10000" ,ngf-min-height="1000" but not work correct because after resize height 169 , and give error minHeight

**Comment by danialfarid** [comment] 2015-12-02 09:10
attach your image here

**Comment by armangevorgyan** [comment] 2015-12-02 09:17
![reggae2](https://cloud.githubusercontent.com/assets/13254080/11526891/a639a7a0-98ee-11e5-8e84-a4b7233e36d5.jpg)

colorflare.libs.js:15672 Valid images ratio 7.994082840236686 ngf-width 1351 ngf-height 169

**Comment by danialfarid** [comment] 2015-12-02 09:57
Selecting it with the demo page create the correct width and height. It should be something with your code.
Try to create a jsfiddle

**Comment by iamisti** [comment] 2015-12-18 18:02
Have the same problem. If you put your original image into a container and fix the size of that container (u have to since the description), then u'll end up with a resized image which dimensions are totally different than the original one.
Please fix it as soon as possible!

**Comment by danialfarid** [comment] 2015-12-19 07:38
That is probably a problem in your code. If you could create a jsfiddle or specify steps to reproduce I could investigate.

**Comment by danialfarid** [comment] 2015-12-19 07:39
Closing this until steps to reproduce are posted.

**Closed by danialfarid** 2015-12-19 07:39 UTC
