### ISSUE TITLE
Send true as boolean rather than "true"

### ISSUE THREAD

**Issue by pavankumarkatakam** [danialfarid/ng-file-upload#900] opened 2015-07-30 11:08 UTC
Im using this plugin for fileupload, in one case i want to send the file as well as some other fields to server, so i have written like this
````

 for (var i = $scope.path.length - 1; i >= 0; i--)
                names.push("pictures[" + i + "]");


 Upload.upload({
                url: 'server/uri',
                fields: $scope.files,
                file: $scope.path,
                fileFormDataName: names,
                sendFieldsAs: 'form',
                formDataAppender: function (formData, key, val) {
                    console.log(formData);
                    console.log(key)
                    console.log(val)
                },
            })
````

where the one key in $scope.files is `is_common` which has boolean value, but when i inspected it in chrome network it is sending as "true", but my server recieves only the boolean true. is there a way to send the values as boolean true rather than "true"

**Comment by danialfarid** [comment] 2015-07-30 15:40
You don't need the formDataAppender.
Can you create a jsfiddle?

**Comment by pavankumarkatakam** [comment] 2015-07-31 12:51
Sorry for late, actually now i dont have resource for making jsfiddle, but i will explain a little bit more, 

if the scope object is

````
$scope.somthing={
  'has_partner':true,
  'physical_location':null
}
````

when i send this object with Upload service along with file object in server im getting the has_partner as "true" and physical_location as "null",but  when i send this object using $http angular service in server im getting has_partner as true (bool type) and physical_location is null (object null). so this is my problem, can you tell me something why it is happening or want jsfiddle

**Comment by danialfarid** [comment] 2015-08-03 20:22
Duplicate of this: https://github.com/danialfarid/ng-file-upload/issues/904
You can send everything as json and parse it on the server.
That would be the only workaround for now I could think of.

**Closed by danialfarid** 2015-08-03 20:22 UTC
