### ISSUE TITLE
xdomain compatibility (ie8/9) 

### ISSUE THREAD

**Issue by undeidentity** [danialfarid/ng-file-upload#760] opened 2015-05-25 07:52 UTC
Hi danialfarid.
I am planning to use xdomain and ng-file-upload 
The problem is both plugin modify XHR object(or something like that) so they have conflict.
The file loads libraries in [xdomain.js -> ng-file-upload-shim.js -> angular.js -> ng-file-upload.js] order.
Is there any way to use them in the same time?
DEMO : http://swb4u2.cafe24.com/xngf/test.html

xdomain side github issue : https://github.com/jpillora/xdomain/issues/151

thanks!

**Comment by danialfarid** [comment] 2015-05-25 12:57
Could you make your demo to use non minified version of xdomain please?

**Comment by undeidentity** [comment] 2015-05-25 13:35
My mistake, sorry. I just fixed it. also added debug="true"

http://swb4u2.cafe24.com/xngf/test2.html < demo without xdomain.

**Comment by undeidentity** [comment] 2015-05-29 14:10
T_T

**Comment by danialfarid** [comment] 2015-05-29 14:51
The issue is that xdomain is using postMessage to send the request headers and that would convert the request headers to json, but in angular you can specify a function as a request header which is what I do in this plugin and this would make converting the headers to json to fail since there is a function value for one of the headers.

This could probably be fixed by xdomain to preprocess the headers before postMessage by removing or applying the function headers.

**Comment by danialfarid** [comment] 2015-06-01 01:36
@undeidentity Can you add this t to your `Upload.upload()` options and see if it solves the problem:
```
transformRequest: function(data, headersGetter){
            var headers = headersGetter();
            headers['__setXHR_'] = undefined;
            return data;
}
```

Thanks

**Comment by kadowki** [comment] 2015-06-11 16:44
@danialfarid I also have this problem and tried this to no avail. I won't be able to provide a demo due to the nature of the app and company. Let me know if more is needed.

Here are some screenshots.

![screen shot 2015-06-11 at 11 42 24 am](https://cloud.githubusercontent.com/assets/5677536/8112669/f63d0ee8-102e-11e5-96de-b47ad201acf1.png)


![untitled](https://cloud.githubusercontent.com/assets/5677536/8112653/d47c4792-102e-11e5-8fd8-6f4c38232be7.png)

**Comment by danialfarid** [comment] 2015-06-16 15:35
Can any of you guys create a jsfiddle showing the error.
Also could you try loading xdomain after ng-file-upload? That could solve the problem.

**Comment by Jandalf** [comment] 2015-10-01 06:45
just encountered the same problem, with ng-file-upload + xdomain when posting cross domain.
your fix with deleting the __setXHR_ property has no effect, the header is still there when xdomain throws the exception. Could be because the error comes from an xhr request created by xdomain (I think xdomain somehow mirrors all request and proxies them through an iframe). would it be possible to disable the  the __setXHR_ property altogether (via a provider config option?), it would be ok to loose the progress indicator.

In our current project structure, it would be hard to load xdomain after ng-file-upload.

**Comment by danialfarid** [comment] 2015-10-01 15:31
@Jandalf could you create a jsfiddle or post the details of the error you get and the browser.

**Comment by danialfarid** [comment] 2015-10-01 15:42
IE8-9 doesn't support FormData so the request is being sent using flash not XMLHttpRequest. So there is no point in using xdomain for them for the file upload: https://github.com/jpillora/xdomain/issues/151#issuecomment-106868189

**Comment by danialfarid** [comment] 2015-10-01 17:01
@Jandalf I added `disableProgress` option to the `Upload.upload()`. See if that would help.

**Closed** 2015-10-02 02:08 UTC
