### ISSUE TITLE
Directives Firing Twice

### ISSUE THREAD

**Issue by fitzpaid** [danialfarid/ng-file-upload#558] opened 2015-02-11 14:17 UTC
Since updating to version 3.0.2 from 3.0.0 I am seeing an issue where all file upload directives are firing twice, so events are being added twice, as are input boxes.

I had a dig through the angular code and it seems to be due to angular registering both angularFileUpload and ngFileUpload - this seems to be related to a commit the other day where;

var ngFileUpload = angular.module('ngFileUpload', []);

for (key in angularFileUpload) {
	ngFileUpload[key] = angularFileUpload[key];
}

was added in.

What can be done to alleviate this problem?

**Comment by danialfarid** [comment] 2015-02-11 14:42
I don't believe it's related to that. You will be including one of those in your app so one will be used. Can you create a jsfiddle? I think what you are seeing is the event firing when you click on the upload button to empty it's value and set it's value to null. That is for allowing selecting the same file again or handling user cancelling the file select popup. So as soon as you click on the button an event will be fired with empty files.

**Comment by clifflo** [comment] 2015-02-18 16:07
I have also faced the same problem. When I click the upload button it would pop up a window for selecting a new file. However, no matter whether I choose a file or simply click cancel, the window would show up again and this time the selection would be valid. So it ends up having twice selecting files of which the first one is invalid. How to solve that?

**Comment by danialfarid** [comment] 2015-02-18 17:15
@clifflo that's a separate issue from what @fitzpaid describes here.
What version of plugin and what browser are you seeing this problem in?
Could you create a jsfiddle to reproduce the problem from the sample jsfiddle on readme?

**Comment by clifflo** [comment] 2015-02-19 08:25
Hi Danial I have fixed it myself. Actually I have used Ionic Framework and I put the uploader within the labels. Once I get the uploader out of the label it works. Perhaps later on I would post a question within Ionic Framework's forum. Anyway thanks for your help.

**Comment by SeyZ** [comment] 2015-02-22 20:17
:+1: When the directive is inside the label, the file upload is fired twice.

**Comment by danialfarid** [comment] 2015-02-22 22:32
@SeyZ can you create a js fiddle showing this? You can use the js fiddle sample on the readme file

**Comment by dberube** [comment] 2015-03-23 20:15
I'm also seeing this happen with Angular 1.2 and MaterializeCSS 0.95.3

See example code here:
https://gist.github.com/dberube/4709a89a5787a72e60d8

**Comment by miqdadalik** [comment] 2015-04-07 18:18
I am also facing same issue

**Comment by danialfarid** [comment] 2015-04-08 19:11
@miqdadalik @dberube could you create a jsfiddle showing the bug?

**Comment by coty-crg** [comment] 2015-04-22 18:06
Chiming in to +1 this, it's happening with me as well.

**Comment by danialfarid** [comment] 2015-04-22 18:11
If you guys could create a jsfiddle or plnkr to reproduce this issue I would fix it.
Is this happening with the latest version?

**Comment by coty-crg** [comment] 2015-04-22 18:13
It's happening on 3.2.4 (installed from bower), yeah.

**Comment by danialfarid** [comment] 2015-04-22 18:17
I cannot seem to reproduce it with the descriptions you have posted here.

**Comment by coty-crg** [comment] 2015-04-22 19:02
Hey danialfarid, I managed to fix it for my company's project by removing the following three lines from the angular-file-upload.js file:

    for (var key in angularFileUpload) {
        ngFileUpload[key] = angularFileUpload[key];
    }

as the first poster suggested.

Everything seems to be working, but I'm not entirely sure what the side effects of this would be. If nothing, then it would be awesome if you made this or a similar change to fix this problem on the official code.

**Comment by danialfarid** [comment] 2015-04-22 19:12
That won't have side effects that is just to let you use both names as the module name. But I cannot see how it could create an issue, it might be the way you reference the module or something that's why I'm asking for a reproducible sample.

**Comment by coty-crg** [comment] 2015-04-22 19:15
It's probably specific to how we have our project setup, because I cannot seem to reproduce the issue outside of the project. 

We are using the MEAN stack, which has a lot of dependencies in itself. I hope this can help you narrow it down, somehow.

**Comment by miqdadalik** [comment] 2015-04-22 19:25
I am getting issue with angularAMD+requireJS

**Comment by john-pettigrew** [comment] 2015-04-22 20:43
We are having the issue with Lumx and angular material. 
http://ui.lumapps.com
https://material.angularjs.org/#/

**Comment by coty-crg** [comment] 2015-04-23 01:02
We have a thing that automatically loads all of our bower packages. I think it thinks your setup which enables both names to be used is actually two separate packages. So when it auto loads up packages it loads yours twice. 

When I get some time I'll fork and do the fix, followed by a pull request to remove the lines I mentioned earlier from the code. I hope you'll accept it.

**Comment by bennekrouf** [comment] 2015-04-28 13:03
I've got the same issue with ionic inside and outside a label.

**Comment by danialfarid** [comment] 2015-04-28 16:47
This is fixed in version 4.x.x.

**Closed by danialfarid** 2015-04-28 16:47 UTC
