### ISSUE TITLE
PUT Method not working

### ISSUE THREAD

**Issue by ssuhat** [danialfarid/ng-file-upload#1037] opened 2015-10-02 11:08 UTC
Hi,

i  got problem when i'm using method: "PUT" when uploading file.

      Upload.upload({
          url: APIROOT + 'categories/' + $routeParams.id,
          data: data,
          method: 'PUT'
      }).then(function (response) {
           ResultService(response.data);
       }, function (response) {
           ResultService(response.data);
       }).finally(function () {
           $scope.loading = false;
           $scope.button_text = "Update";
       });

At my server i can't receive the data. But if i change method to "POST" i can receive it properly. 

Any solution?

**Comment by danialfarid** [comment] 2015-10-02 15:18
Is there any change in the network tab of your browser between put and post? other than method?

**Comment by paambaati** [comment] 2015-10-07 09:49
Can confirm; I have the same issue. POST works, while PUT doesn't. Nothing else changed. FWIW, the backend is built on Grails, and uses the native `MultipartHttpServletRequest` class to read the data.

**Comment by danialfarid** [comment] 2015-10-07 20:38
Since it's a server side issue closing this

**Closed by danialfarid** 2015-10-07 20:38 UTC

**Comment by danialfarid** [comment] 2015-12-23 16:57
Make sure you don't set the content-type when you are using Upload.upload() that could be the problem.

**Comment by ebarthelemy** [comment] 2016-04-28 17:52
Dear Danial,

I face the same issue when I use your ng-file-upload directive for a PUT request: my API doesn't receive any data.

```
Upload.upload({
    url: 'http://.../api/v1/places/' + $stateParams.placeId,
    data: $scope.formModel,
    method: 'PUT',
    headers: {'Authorization': 'Bearer ' + $scope.Auth.token},
}).then(function (resp) {
        ...
```

If I change the method from PUT to POST, it works, but it means that I have to change the endpoint in my API which is something I don't necessarily want to do.

If I use the classic $http directive, it works:

```
$http.defaults.headers.common.Authorization = 'Bearer ' + $scope.Auth.token;
$http.put('http://.../api/v1/places/' + $stateParams.placeId, $scope.formModel).
    success(function (data) {
        ...
```

By default, my content-type is:

```
Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryH31DTujPdxLGLBzp
```

I really wish I could use your ng-file-upload directive for a PUT request without changing the method from PUT to POST neither the end point in my API.

Do you have any idea how I could do so?

Thank you for your time and consideration.

**Comment by ebarthelemy** [comment] 2016-04-28 17:57
I really wish I could use your ng-file-upload directive for a PUT request without changing the method from PUT to POST neither the end point in my API.

Do you have any idea how I could do so?

Thank you for your time and consideration.

**Comment by danialfarid** [comment] 2016-05-06 22:24
Can you get any PUT request working using ajax or curl? This way we know if the issue is the backend or front-end

**Comment by ssuhat** [comment] 2016-05-07 01:46
I think it's on front end. I use PUT method sometimes only on file upload I need to use POST because PUT not sending any data. I'm using Laravel for my backend

**Comment by danialfarid** [comment] 2016-05-07 12:42
I meant a PUT request that is sending a file. Maybe backend won't accept PUT request multipart form data with file binary or maybe some headers are needed for that.

**Comment by ebarthelemy** [comment] 2016-05-09 16:38
Thank you for your answers guys. I realize that you can do a PUT request for an update only if there's no file attached (x-www-form-urlencoded not for big data like files...). In the case of an attached file, if you want to update the file attached with your form for example, you have to do a POST request with a _method = 'PUT' parameter to specifies that you want to use PUT instead of POST (form-data). PEACE

**Comment by ngodfraind** [comment] 2016-05-25 15:51
Hello, same issue here

This doesn't work:

```
return this.Upload.upload({
    url: url,
    data: parameters,
    method: 'PUT'
})
```

This works

```
return this.$http.put(
    url,
    this.$httpParamSerializerJQLike(parameters),
    {headers: {'Content-Type': 'application/x-www-form-urlencoded'}}
)
```

My form didn't contain any file. The backend is Symfony2 with php, but even when I'm trying to retrieve the data manually, php screws up (it looks like something was not formatted / escaped properly).

If you're familar with php, this is the output of the parsed request (I think that's what php frameworks do but I'm not sure).

```
 parse_str(file_get_contents('php://input'), $put);
 var_dump($put);
```

```
array(1) {
  ["------WebKitFormBoundaryFmwnOjVkWAATzm3Z
Content-Disposition:_form-data;_name"]=>
  string(614) ""facet[id]"

1
------WebKitFormBoundaryFmwnOjVkWAATzm3Z
Content-Disposition: form-data; name="facet[name]"

sdfsdf gdfg dfgff
------WebKitFormBoundaryFmwnOjVkWAATzm3Z
Content-Disposition: form-data; name="facet[position]"

0
------WebKitFormBoundaryFmwnOjVkWAATzm3Z
Content-Disposition: form-data; name="facet[force_creation_form]"

false
------WebKitFormBoundaryFmwnOjVkWAATzm3Z
Content-Disposition: form-data; name="facet[is_main]"

false
------WebKitFormBoundaryFmwnOjVkWAATzm3Z
Content-Disposition: form-data; name="facet[$hashKey]"

object:3
------WebKitFormBoundaryFmwnOjVkWAATzm3Z--
"
}

```

I think array shoud be something like instead 

```
['facet' => ['id => 1, 'name' => 'myName']]
```

I'm noticing I should remove the hashKey but it's unrelated (I did it for an other form and it still didn't work).

**Comment by aravindnet** [comment] 2016-06-02 19:34
I am also facing same issue. with httppost it is working but with HttpPut i am not able to read file . i am using .net web api as bak **Unexpected end of MIME multipart stream. MIME multipart message is not complete.** with httpput

**Comment by achiduku** [comment] 2016-07-04 13:41
Same issue. When the method is POST my Laravel API receives data but none with PUT

**Comment by amirhosseini95** [comment] 2016-07-13 22:36
Same issue

**Comment by ssuhat** [comment] 2016-07-14 01:41
I've got a solution and right now I'm still using it.

For example:

   {file: 'abc.jpg'}

Add extra object to your data:

   {_method: 'PUT', file: 'abc.jpg'}

Its working for me. tested on Laravel.

Now laravel will assume that you want PUT method.
