### ISSUE TITLE
UI issues when styling with Bootstrap's btn-group-justified

### ISSUE THREAD

**Issue by seshadrik** [danialfarid/ng-file-upload#629] opened 2015-03-18 18:49 UTC
I am having issues when styling (select file container) with Bootstrap's btn-group-justified. The issue is noticeable when you click cancel in the choose file dialog. Can you please take a look at http://jsfiddle.net/oftxsmbp/1/ and let me know what am I doing wrong?

**Comment by danialfarid** [comment] 2015-03-18 18:52
What the issue is?

**Comment by seshadrik** [comment] 2015-03-18 18:55
The button gets totally resized to almost zero width.

**Comment by danialfarid** [comment] 2015-03-19 14:36
What browser?

**Comment by seshadrik** [comment] 2015-03-19 14:47
I was trying it in chrome
________________________________

**Comment by danialfarid** [comment] 2015-04-13 22:06
Fixed in version 3.3.0

**Closed by danialfarid** 2015-04-13 22:06 UTC
